const webpack = require('webpack');
const path = require('path');
const glob = require('glob');
const ReplaceInFileWebpackPlugin = require("./js/helpers/ReplaceInFileWebpackPluginCustom.js");
var fs = require('fs');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');


// needed to enable mediaQueries variables in comp scss
// read '_variables.css'
const str = fs.readFileSync(__dirname + '/css/defs/_variables.css').toString();
var mediaQueriesArray = [];

// regex to match all media queries variables
var regex = /(?<=@custom-media ).+?(?=;)/g;
var result = str.match(regex);

// build search/replace array to use with 'ReplaceInFileWebpackPlugin'
result.forEach(element => {
    let search = [element.split(/ (.*)/s)[0]];
    search = new RegExp(search, 'g');
    let replace = element.split(/ (.*)/s)[1];
    replace = replace.replace(/\\(/g, '').replace(/\\)/g, '')


    mediaQueriesArray.push({
        search: search,
        replace: replace
    })
});


// patternToEntries - function to get all files from folder
const patternToEntries = (pattern, suffix = '') => glob
    .sync(pattern)
    .reduce((acc, val) => ({
        ...acc,
        [path.basename(val, path.extname(val)) + suffix]: val,
    }), {});

module.exports = {
    devtool: 'hidden-source-map',  // Enable source maps - without add source maps to the output file, it will be added dynamically with shopify asset pipe - {{my_script.js | asset_url | script_tag}}
    entry: {
        bundle: {
            import: './js/theme.js',
            filename: '../assets/[name].js'
        },
        ...patternToEntries('./components/**/*.ts', '')
    },

    output: {
        path: path.resolve(__dirname, './snippets'),  // Output to 'snippets' folder for compiled web components
        publicPath: '/',
    },

    module: {
        rules: [
            {
                test: /\.tsx?$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: path.resolve('./js/helpers/track-liquid-loader.js'),  // Our custom dependency-tracking loader
                    },
                    {
                        loader: 'ts-loader',  // Transpile TypeScript
                        options: {
                            compilerOptions: {
                                sourceMap: true,  // Enable source maps for TypeScript
                            },
                        },
                    },
                    {
                        loader: path.resolve('./js/helpers/inject-html-loader.js'),  // Our custom loader for HTML injection
                    },
                ],
            },
            {
                test: /\.(css|scss)$/,
                use: [
                    'lit-scss-loader', // Compiles SCSS to CSS in Lit-style
                    'sass-loader',     // Translates Sass to CSS
                ],
            },
            // css
            {
                test: /\.(css)$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    {
                        loader: 'css-loader',
                        options: {
                            url: false,
                        },
                    },
                    'postcss-loader',
                ],
            },
            {
                test: /\.liquid$/,
                use: 'html-loader'  // Allows importing HTML templates as modules
            },
            {
                test: /\.(js)$/i,
                exclude: /node_modules/,
                use: ['babel-loader'],
            },
        ],
    },

    plugins: [
        new webpack.SourceMapDevToolPlugin({
            filename: '../assets/[name].js.map',
            append: "\\n//# sourceMappingURL={{ '[name].js.map' | asset_url }}",
            module: true,
            columns: true,
        }),
        new webpack.BannerPlugin("\\n\\n\tThis file is auto generated by webpack.\\n\tDo not edit this file directly.\\n\\n"),
        new webpack.ProvidePlugin({
            Turbo: "@hotwired/turbo"
        }),
        // extract css from js files to separate files
        new MiniCssExtractPlugin({
            filename: '../snippets/[name].css.liquid',
        }),
        new ReplaceInFileWebpackPlugin([
            {
                dir: 'snippets',
                test: [/\.js\.liquid$/], // Target files with the '.js.liquid' extension
                rules: [
                    // for liquid variables in js&css files
                    {
                        search: /['"]{{/g,
                        replace: '{{',
                    },
                    {
                        search: /}}['"]/g,
                        replace: '}}',
                    },
                    // for media queries variables in css files
                    ...mediaQueriesArray
                ],
            },
        ]),
        // Add a plugin to rename files after they are generated
        {
            apply: (compiler) => {
                compiler.hooks.emit.tapAsync('RenameFilesPlugin', (compilation, callback) => {
                    Object.keys(compilation.assets).forEach((filename) => {
                        if (filename.endsWith('.js')) {
                            const newFilename = filename.replace('.js', '.js.liquid');
                            compilation.assets[newFilename] = compilation.assets[filename];
                            delete compilation.assets[filename];
                        }
                    });
                    callback();
                });
            }
        }
    ],

    resolve: {
        extensions: ['.scss', '.css', '.js', '.ts', '.liquid'],
        alias: {
            'shopify-api-js': path.resolve(__dirname, 'node_modules/shopify-api-js/lib/ShopifyFrontendHelper.js')
        }
    },

    optimization: {
        minimize: false
    }
};
